// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoC.Context;

#nullable disable

namespace PoC.Migrations
{
    [DbContext(typeof(ShareLoginDatabaseContext))]
    [Migration("20220905072702_change-controller-user")]
    partial class changecontrolleruser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AccessLoginUser", b =>
                {
                    b.Property<int>("AccessLoginsIdAccessLogin")
                        .HasColumnType("int");

                    b.Property<int>("UsersIdUser")
                        .HasColumnType("int");

                    b.HasKey("AccessLoginsIdAccessLogin", "UsersIdUser");

                    b.HasIndex("UsersIdUser");

                    b.ToTable("AccessLoginUser");
                });

            modelBuilder.Entity("PoC.Models.AccessLogin", b =>
                {
                    b.Property<int>("IdAccessLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccessLogin"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlataformLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAccessLogin");

                    b.ToTable("AccessLogin");
                });

            modelBuilder.Entity("PoC.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PoC.Models.UserLogin", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdAccessLogin")
                        .HasColumnType("int");

                    b.HasKey("IdUser", "IdAccessLogin");

                    b.HasIndex("IdAccessLogin");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("AccessLoginUser", b =>
                {
                    b.HasOne("PoC.Models.AccessLogin", null)
                        .WithMany()
                        .HasForeignKey("AccessLoginsIdAccessLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoC.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersIdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoC.Models.UserLogin", b =>
                {
                    b.HasOne("PoC.Models.AccessLogin", "AccessLogin")
                        .WithMany()
                        .HasForeignKey("IdAccessLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoC.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLogin");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
